revert deleting the methods `log_`*, because we use them in many other projects

diff --git a/src/releaser b/src/releaser
--- a/src/releaser
+++ b/src/releaser
@@ -32,6 +32,22 @@ releaser_log_error() {
 releaser_log_warn() {
   echo -e "\e[33m$(LANG=en_US date "+%d-%m-%Y %T") $(releaser_program_name) warn: $1\e[0m" >&2
 }
+log_debug() {
+  if [ "${RELEASER_LOG_LEVEL}" == "debug" ]; then
+    echo -e "$(LANG=en_US date "+%d-%m-%Y %T") $(releaser_program_name) debug: ${1}" >&2
+  fi
+}
+log_info() {
+  echo -e "$(LANG=en_US date "+%d-%m-%Y %T") $(releaser_program_name) info: ${1}" >&2
+}
+log_error() {
+  echo -e "\e[31m$(LANG=en_US date "+%d-%m-%Y %T") $(releaser_program_name) error: $1\e[0m" >&2
+  echo -e "\e[31m$(LANG=en_US date "+%d-%m-%Y %T") $(releaser_program_name) error: File: ${BASH_SOURCE[0]}\e[0m" >&2
+  echo -e "\e[31m$(LANG=en_US date "+%d-%m-%Y %T") $(releaser_program_name) error: Line numbers: ${BASH_LINENO[*]}\e[0m" >&2
+}
+log_warn() {
+  echo -e "\e[33m$(LANG=en_US date "+%d-%m-%Y %T") $(releaser_program_name) warn: $1\e[0m" >&2
+}
 
 # In order to load all the releaser functions once you can run:
 # releaser_loaded || eval "$(curl http://gogs.ai-traders.com/platform/releaser/raw/0.2.0/src/releaser)"
