updated readme on how to install releaser; releaser_loaded function to load releaser functions once

diff --git a/src/releaser b/src/releaser
--- a/src/releaser
+++ b/src/releaser
@@ -18,21 +18,31 @@ set -e
 # Each log output goes to stderrr, so that we can return value from functions
 # with stdout. (Curl does the same).
 
+program_name() {
+  echo "RELEASER"
+}
 log_debug() {
   if [ "$RELEASER_LOG_LEVEL" == "debug" ]; then
-    echo -e "$(date "+%d-%m-%Y %T") RELEASER debug: ${1}" >&2
+    echo -e "$(date "+%d-%m-%Y %T") $(program_name) debug: ${1}" >&2
   fi
 }
 log_info() {
-  echo -e "$(date "+%d-%m-%Y %T") RELEASER info: ${1}" >&2
+  echo -e "$(date "+%d-%m-%Y %T") $(program_name) info: ${1}" >&2
 }
 log_error() {
-  echo -e "\e[31m$(date "+%d-%m-%Y %T") RELEASER error: $1\e[0m" >&2
-  echo -e "\e[31m$(date "+%d-%m-%Y %T") RELEASER error: File: ${BASH_SOURCE[0]}\e[0m" >&2
-  echo -e "\e[31m$(date "+%d-%m-%Y %T") RELEASER error: Line numbers: ${BASH_LINENO[*]}\e[0m" >&2
+  echo -e "\e[31m$(date "+%d-%m-%Y %T") $(program_name) error: $1\e[0m" >&2
+  echo -e "\e[31m$(date "+%d-%m-%Y %T") $(program_name) error: File: ${BASH_SOURCE[0]}\e[0m" >&2
+  echo -e "\e[31m$(date "+%d-%m-%Y %T") $(program_name) error: Line numbers: ${BASH_LINENO[*]}\e[0m" >&2
 }
 log_warn() {
-  echo -e "\e[33m$(date "+%d-%m-%Y %T") RELEASER warn: $1\e[0m" >&2
+  echo -e "\e[33m$(date "+%d-%m-%Y %T") $(program_name) warn: $1\e[0m" >&2
+}
+
+# In order to load all the releaser functions once you can run:
+# releaser_loaded || eval "$(curl http://gogs.ai-traders.com/platform/releaser/raw/0.2.0/src/releaser)"
+# Or you can simply wget that file and source it.
+function releaser_loaded {
+  return 0
 }
 
 # Arguments:
